<?php

declare(strict_types=1);

namespace AssoConnect\PHPSP\DataInterface\Wallet;

use AssoConnect\PHPSP\DataInterface\PspLifecycleAwareInterface;

interface PspSubWalletInterface extends PspLifecycleAwareInterface
{
    /**
     * Returns this sub-wallet's reference in the application system.
     * This value has to be generated by the application.
     *
     * @return string|null
     */
    public function getAppId(): ?string;

    /**
     * Returns this sub-wallet's reference in the PSP system.
     * This value is generated by the PSP.
     *
     * @return string|null
     */
    public function getPspId(): ?string;

    /**
     * Sets this sub-wallet's reference in the PSP system.
     *
     * @param string $pspId
     * @return $this
     */
    public function setPspId(string $pspId): self;

    /**
     * Returns this sub-wallet's parent
     *
     * @return PspWalletInterface
     */
    public function getPspWallet(): PspWalletInterface;

    /**
     * Returns the label to use with incoming transfers to credit this sub-wallet.
     *
     * @return string|null
     */
    public function getPspTransferLabel(): ?string;

    /**
     * Sets the label to use with incoming transfers to credit this sub-wallet.
     *
     * @param string $pspTransferLabel
     * @return $this
     */
    public function setPspTransferLabel(string $pspTransferLabel): self;

    /**
     * Returns the name of the entity owning this sub-wallet.
     * If supported, this name will be used as the sub-wallet's name in the PSP system.
     * @return string
     */
    public function getBusinessName(): string;
}
